language: node_js

node_js:
  - '6'
  - '8'
  - 'lts/*'
  - 'node'

cache:
  directories:
    - "node_modules"

services:
  - postgresql

before_script:
  - psql -c 'create database keysetpaging_test;' -U postgres
