language: node_js

node_js:
  - '8'
  - '10'
  - 'node'

cache:
  directories:
    - "node_modules"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE keysetpaging_test;" -U postgres
  - psql -c "CREATE USER keyset WITH password 'no-offset';" -U postgres
